---

- name: Launching EC2 Instance
  ec2:
    key_name: "{{ keypair }}"
    instance_type: "{{ instance }}"
    image: "{{ image }}"
    region: "{{ aws_region }}"
    exact_count: "{{ count }}"
    wait: yes
    group: "{{ sg_name }}"
    vpc_subnet_id: "{{ minichat_subnet.subnet.id }}"
    count_tag: 
      Name: "{{ server_name }}"
  register: ec2

- name: Associate an elastic IP 
  ec2_eip:
    ip: "{{ elastic_ip }}"
    region: "{{ aws_region }}"
    device_id: "{{ item }}"
  with_items: "{{ ec2.instance_ids }}"

